spring:
  application:
    name: autoee-busi-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      
        
server:
  port: 8082
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
   