spring:
  application:
    name: autoee-feign-sentinel-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      
        
server:
  port: 8084

feign:
  sentinel:
    enabled: true
              
management:
  endpoints:
    web:
      exposure:
        include: "*"
   